// Auto-generated by add_indices.py
import NORMALIZED_PLACE_IDX from "./NORMALIZED_PLACE_IDX";
import STYLE from "./STYLE";
import VERSION from "./VERSION";

export { NORMALIZED_PLACE_IDX, STYLE, VERSION };
